Fix bin/heroku-api
Currently when you try to run `bin/heroku-api` you get an error:

```
$ bundle exec bin/heroku-api
bundler: failed to load command: bin/heroku-api (bin/heroku-api)
NameError: uninitialized constant Moneta
  bin/heroku-api:12:in `<top (required)>'
```

This is happening because the `moneta` library is present but not required.

This PR fixes this issue by requiring the library.